/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/alon_house/house_scene-v1.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Boom_Dance' | 'Breakdance_1990' | 'Fall1' | 'Hip_Hop_Dance_3' | 'Idle_3' | 'Running' | 'Walking'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    colisiones: THREE.Mesh
    body_1: THREE.Mesh
    body_1_1: THREE.Mesh
    Lamborghini_Aventador: THREE.Mesh
    Lamborghini_Aventador_1: THREE.Mesh
    house: THREE.Mesh
    floor_main: THREE.Mesh
    hedge_straight_long: THREE.Mesh
    Grass_Large_Extruded: THREE.Mesh
    pool: THREE.Mesh
    char1: THREE.SkinnedMesh
    Hips: THREE.Bone
  }
  materials: {
    tire_mat: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    _Lamborghini_AventadorLamborghini_Aventador_BodySG: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    ['tripo_mat_1e802364-a22a-44bc-ab33-ab07f9b073a6']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    tiny_treats_1: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Material_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/house_scene-v1.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-188.385, 21.932, 86.751]} rotation={[0.073, 1.155, 3.075]} scale={-0.077}>
          <primitive object={nodes.Hips} />
        </group>
        <mesh name="colisiones" geometry={nodes.colisiones.geometry} material={nodes.colisiones.material} />
        <group name="banana_vehicle">
          <mesh name="body_1" geometry={nodes.body_1.geometry} material={materials.tire_mat} />
          <mesh name="body_1_1" geometry={nodes.body_1_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="lambo_vehicle">
          <mesh name="Lamborghini_Aventador" geometry={nodes.Lamborghini_Aventador.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
          <mesh name="Lamborghini_Aventador_1" geometry={nodes.Lamborghini_Aventador_1.geometry} material={materials.PaletteMaterial002} />
        </group>
        <mesh name="house" geometry={nodes.house.geometry} material={materials['tripo_mat_1e802364-a22a-44bc-ab33-ab07f9b073a6']} />
        <mesh name="floor_main" geometry={nodes.floor_main.geometry} material={materials.PaletteMaterial003} />
        <mesh name="hedge_straight_long" geometry={nodes.hedge_straight_long.geometry} material={materials.tiny_treats_1} position={[89.614, 0, 0]} />
        <mesh name="Grass_Large_Extruded" geometry={nodes.Grass_Large_Extruded.geometry} material={materials.Grass} position={[56.741, 0, 9.279]} scale={0.977} />
        <mesh name="pool" geometry={nodes.pool.geometry} material={materials['Material.001']} position={[22.277, 3.593, 94.081]} scale={3.072} />
        <skinnedMesh name="char1" geometry={nodes.char1.geometry} material={materials.Material_1} skeleton={nodes.char1.skeleton} position={[-188.385, 21.932, 86.751]} rotation={[-3.069, -1.155, -3.075]} scale={[-0.077, 0.077, 0.077]} />
      </group>
    </group>
  )
}

useGLTF.preload('/house_scene-v1.glb')
